name: link_directory
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
